apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jakubmroz4/backend4
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: PYTHONUNBUFFERED
          value: 1
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "flask_db"
        - name: POSTGRES_HOST
          value: "db"
        - name: DATABASE_PORT
          value: 5432
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10