services:
  backend:
    image: jakubmroz4/backend3
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  frontend:
    image: jakubmroz4/frontend3
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_APIURL=http://localhost:5000
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  node-modules: