services:
  backend:
    restart: always
    image: jakubmroz4/backend4
    links:
      - db:db
    command: >
      sh -c "python3 ./create_db.py &&
             flask run --host=0.0.0.0"
    volumes:
      - ./backend:/app
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: app.py      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
      POSTGRES_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: jakubmroz4/frontend4
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_APIURL=http://localhost:5000
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db:
    restart: always
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    ports:
    - "5432:5432"

volumes:
  node-modules:
  postgres_data: